# Copyright (c) 2019. www.hydrologis.com. All rights reserved.
# Use of this source code is governed by a GPL3 license that can be
# found in the LICENSE file.
name: smash
description: The open source digital field mapping app.
version: 0.2.0+0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # Apache 2
  badges: ^1.1.0

  # BSD
  package_info: ^0.4.0+13


  # ON IOS TO EXPOSE STORAGE FOLLOWING KEYS ARE NEEDED
  #    <key>LSSupportsOpeningDocumentsInPlace</key>
  #    <true/>
  #    <key>UIFileSharingEnabled</key>
  #    <true/>


  # MIT
  geolocator: ^5.1.5
  # on IOS heading is not supported. For rotation we should try the plugin: location: 2.3.5
  # ON IOS NEEDS:
  #  <key>NSLocationWhenInUseUsageDescription</key>
  #  <string>The app needs access to location when open to allow the user to map geographic data on the territory.</string>
  #  <key>NSLocationAlwaysAndWhenInUseUsageDescription</key>
  #  <string>The app needs access to location in background to be able to log geographic shapes on the territory also while walking with the screen off or during phone calls.</string>
  #  <key>NSLocationAlwaysUsageDescription</key>
  #  <string>The app needs access to location in background to be able to log geographic shapes on the territory also while walking with the screen off or during phone calls.</string>

  # MIT
  sqflite: ^1.2.0

  #BSD
  dart_jts: 0.0.4+2
  # apache 2
  flutter_geopackage: #0.0.1
    git:
      url: https://github.com/moovida/flutter_geopackage.git

  #BSD
  image_picker: ^0.6.3
  # ON IOS NEEDS:
  #  <key>NSPhotoLibraryUsageDescription</key>
  #  <string>The app needs to access the photo library to attach media to the survey.</string>
  #  <key>NSCameraUsageDescription</key>
  #  <string>The app needs to use the camera to take picture notes during the field mapping activity.</string>
  #  <key>NSMicrophoneUsageDescription</key>
  #  <string>The app needs to use the camera to take vocal notes during the field mapping activity.</string>

  # apache
  latlong: 0.6.1

  # MIT
  material_design_icons_flutter: ^3.4.4795

  # BSD
  path_provider: ^1.5.1

  # MIT
  path_provider_ex: ^1.0.1

  # MIT
  screen: 0.0.5
  # ON ANDROID NEEDS:
  # <uses-permission android:name="android.permission.WAKE_LOCK" />

  # UNKNOWN!!!
  geocoder: 0.2.1

  # BSD
  shared_preferences: ^0.5.6

  # MIT
  logger: ^0.8.2

  # BSD
  #  esys_flutter_share: any #1.0.2

  # UNKNOWN!!!
  animated_floatactionbuttons: ^0.1.0

  # MIT
  flutter_material_color_picker: ^1.0.5

  # BSD
  flutter_map: #^0.8.1
    git:
      url: https://github.com/moovida/flutter_map.git

  flutter_map_marker_cluster: #^0.2.5
    git:
      url: https://github.com/moovida/flutter_map_marker_cluster.git



  ## USING OWN FILEPICKER TO AVOID PATHS CAOS
  # MIT
  #  file_picker: ^1.4.3+1
  # ON IOS NEEDS:
  #  <key>UIBackgroundModes</key>
  #  <array>
  #  <string>fetch</string>
  #  <string>remote-notification</string>
  #  </array>

  #MIT
  extended_image: ^0.6.8

  # MIT
  permission_handler: ^4.0.0

  # BSD
  stack_trace: 1.9.3

  # MIT
  share_extend: ^1.1.0

  # BSD
  url_launcher: ^5.4.1

  # MIT
  dio: ^3.0.8

  # Apache 2.0
  gpx: ^0.0.3

  # Apache 2.0
  pdf: ^1.3.25

  # MIT
  flutter_tags: ^0.4.5

  # MIT
  flutter_datetime_picker: ^1.3.1

  mapsforge_flutter:
    git:
      url: https://github.com/moovida/mapsforge_flutter.git
      ref: libs_upgrade
      path: mapsforge_flutter
    #path: ../../OTHERS/mapsforge_flutter/mapsforge_flutter


dev_dependencies:

  # MIT
  flutter_launcher_icons: ^0.7.4

  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: false
  image_path_ios: "assets/ic_launcher_ios.png"
  image_path_android: "assets/ic_launcher_ios.png"
  adaptive_icon_background: "assets/ic_launcher_ios.png"
  adaptive_icon_foreground: "assets/ic_launcher_ios.png"
  # to rebuild icons run: flutter packages pub run flutter_launcher_icons:main


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/tags.json
    - assets/geopaparazzi_launcher_icon.svg
    - assets/gpicon.png
    - assets/emptytile256.png
    - assets/maptools_icon.png
    - assets/smash_icon.png
    - assets/smash_logo_64.png
    - assets/smash_text.png
    - assets/defaultrender.xml
    - packages/mapsforge_flutter/assets/patterns/coniferous.svg
    - packages/mapsforge_flutter/assets/patterns/coniferous_and_deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/farmland.svg
    - packages/mapsforge_flutter/assets/patterns/grass.svg
    - packages/mapsforge_flutter/assets/patterns/hills.svg
    - packages/mapsforge_flutter/assets/patterns/quarry.svg
    - packages/mapsforge_flutter/assets/patterns/scrub.svg
    - packages/mapsforge_flutter/assets/patterns/swamp.svg
    - packages/mapsforge_flutter/assets/patterns/access-destination.png
    - packages/mapsforge_flutter/assets/patterns/access-private.png
    - packages/mapsforge_flutter/assets/patterns/arrow.png
    - packages/mapsforge_flutter/assets/patterns/cemetery.png
    - packages/mapsforge_flutter/assets/patterns/coniferous.svg
    - packages/mapsforge_flutter/assets/patterns/coniferous_and_deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/deciduous.svg
    - packages/mapsforge_flutter/assets/patterns/dot.png
    - packages/mapsforge_flutter/assets/patterns/farmland.svg
    - packages/mapsforge_flutter/assets/patterns/grass.svg
    - packages/mapsforge_flutter/assets/patterns/hills.svg
    - packages/mapsforge_flutter/assets/patterns/marsh.png
    - packages/mapsforge_flutter/assets/patterns/military.png
    - packages/mapsforge_flutter/assets/patterns/nature-reserve.png
    - packages/mapsforge_flutter/assets/patterns/pike.png
    - packages/mapsforge_flutter/assets/patterns/quarry.svg
    - packages/mapsforge_flutter/assets/patterns/rail.png
    - packages/mapsforge_flutter/assets/patterns/scrub.svg
    - packages/mapsforge_flutter/assets/patterns/swamp.svg
    - packages/mapsforge_flutter/assets/patterns/wood-coniferous.png
    - packages/mapsforge_flutter/assets/patterns/wood-deciduous.png
    - packages/mapsforge_flutter/assets/patterns/wood-mixed.png
    - packages/mapsforge_flutter/assets/symbols/bench.svg
    - packages/mapsforge_flutter/assets/symbols/cable_car.svg
    - packages/mapsforge_flutter/assets/symbols/chair_lift.svg
    - packages/mapsforge_flutter/assets/symbols/dot_black.svg
    - packages/mapsforge_flutter/assets/symbols/dot_blue.svg
    - packages/mapsforge_flutter/assets/symbols/dot_blue_dark.svg
    - packages/mapsforge_flutter/assets/symbols/dot_magenta.svg
    - packages/mapsforge_flutter/assets/symbols/dot_white.svg
    - packages/mapsforge_flutter/assets/symbols/gondola.svg
    - packages/mapsforge_flutter/assets/symbols/oneway.svg
    - packages/mapsforge_flutter/assets/symbols/peak.svg
    - packages/mapsforge_flutter/assets/symbols/railway-crossing-small.svg
    - packages/mapsforge_flutter/assets/symbols/railway-crossing.svg
    - packages/mapsforge_flutter/assets/symbols/traffic_signal.svg
    - packages/mapsforge_flutter/assets/symbols/volcano.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/alpinehut.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/camping.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/caravan_park.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/chalet.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/hostel.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/hotel2.svg
    - packages/mapsforge_flutter/assets/symbols/accommodation/shelter2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/firestation3.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/fountain2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/library.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/playground.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/police2.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/post_box.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/post_office.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/recycling.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/telephone.svg
    - packages/mapsforge_flutter/assets/symbols/amenity/toilets.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/blocks.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/bollard.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/cycle_barrier.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/gate.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/lift_gate.svg
    - packages/mapsforge_flutter/assets/symbols/barrier/stile.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/fountain2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/library.svg
    - packages/mapsforge_flutter/assets/symbols/custom/amenity/toilets.svg
    - packages/mapsforge_flutter/assets/symbols/custom/money/atm2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/archaeological2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/attraction.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/castle2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/cinema2.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/information.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/memorial.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/monument.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/museum.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/ruin.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/theatre.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/view_point.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/windmill.svg
    - packages/mapsforge_flutter/assets/symbols/custom/tourist/zoo.svg
    - packages/mapsforge_flutter/assets/symbols/education/nursery3.svg
    - packages/mapsforge_flutter/assets/symbols/education/school.svg
    - packages/mapsforge_flutter/assets/symbols/education/university.svg
    - packages/mapsforge_flutter/assets/symbols/food/bar.svg
    - packages/mapsforge_flutter/assets/symbols/food/biergarten.svg
    - packages/mapsforge_flutter/assets/symbols/food/cafe.svg
    - packages/mapsforge_flutter/assets/symbols/food/drinkingtap.svg
    - packages/mapsforge_flutter/assets/symbols/food/fastfood.svg
    - packages/mapsforge_flutter/assets/symbols/food/pub.svg
    - packages/mapsforge_flutter/assets/symbols/food/restaurant.svg
    - packages/mapsforge_flutter/assets/symbols/health/doctors2.svg
    - packages/mapsforge_flutter/assets/symbols/health/hospital.svg
    - packages/mapsforge_flutter/assets/symbols/health/pharmacy.svg
    - packages/mapsforge_flutter/assets/symbols/money/atm2.svg
    - packages/mapsforge_flutter/assets/symbols/money/bank2.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/buddhist.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/christian.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/hindu.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/islamic.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/jewish.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/shinto.svg
    - packages/mapsforge_flutter/assets/symbols/place_of_worship/unknown.svg
    - packages/mapsforge_flutter/assets/symbols/poi/cave.svg
    - packages/mapsforge_flutter/assets/symbols/poi/embassy2.svg
    - packages/mapsforge_flutter/assets/symbols/poi/mountain_pass.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/alcohol.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/bakery.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/bicycle.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/book.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/butcher.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/car_repair.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/convenience.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/diy.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/greengrocer.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/laundrette.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/marketplace.svg
    - packages/mapsforge_flutter/assets/symbols/shopping/supermarket.svg
    - packages/mapsforge_flutter/assets/symbols/sport/golf.svg
    - packages/mapsforge_flutter/assets/symbols/sport/shooting.svg
    - packages/mapsforge_flutter/assets/symbols/sport/soccer.svg
    - packages/mapsforge_flutter/assets/symbols/sport/stadium.svg
    - packages/mapsforge_flutter/assets/symbols/sport/swimming_outdoor.svg
    - packages/mapsforge_flutter/assets/symbols/sport/tennis.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/archaeological2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/attraction.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/castle2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/cinema2.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/information.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/memorial.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/monument.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/museum.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/picnic.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/ruin.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/theatre.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/view_point.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/windmill.svg
    - packages/mapsforge_flutter/assets/symbols/tourist/zoo.svg
    - packages/mapsforge_flutter/assets/symbols/transport/airport2.svg
    - packages/mapsforge_flutter/assets/symbols/transport/bus_station.svg
    - packages/mapsforge_flutter/assets/symbols/transport/bus_stop.svg
    - packages/mapsforge_flutter/assets/symbols/transport/fuel.svg
    - packages/mapsforge_flutter/assets/symbols/transport/helicopter.svg
    - packages/mapsforge_flutter/assets/symbols/transport/lighthouse.svg
    - packages/mapsforge_flutter/assets/symbols/transport/parking.svg
    - packages/mapsforge_flutter/assets/symbols/transport/parking_private.svg
    - packages/mapsforge_flutter/assets/symbols/transport/rental_bicycle.svg
    - packages/mapsforge_flutter/assets/symbols/transport/slipway.svg
    - packages/mapsforge_flutter/assets/symbols/transport/traffic_lights.svg
    - packages/mapsforge_flutter/assets/symbols/transport/train_station2.svg
    - packages/mapsforge_flutter/assets/symbols/transport/tram_stop.svg
    - packages/mapsforge_flutter/assets/symbols/water/weir.svg
    - packages/mapsforge_flutter/assets/symbols/windsock.svg
    - packages/mapsforge_flutter/assets/symbols/viewpoint.svg




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
